// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ8e-UnCJZGa8rs9m7F7J2BHyD4dSmu1U',
    appId: '1:752229000791:web:9186ad0ebb606267a8a512',
    messagingSenderId: '752229000791',
    projectId: 'where-s-the-halal-auth',
    authDomain: 'where-s-the-halal-auth.firebaseapp.com',
    storageBucket: 'where-s-the-halal-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08a8__V6h_zrFXCvUuYpOJnHdd57BYh0',
    appId: '1:752229000791:android:e62882dc06bc966da8a512',
    messagingSenderId: '752229000791',
    projectId: 'where-s-the-halal-auth',
    storageBucket: 'where-s-the-halal-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAZVmSZLcWtEeHf2UL-NTKYr7FeYI3GRU',
    appId: '1:752229000791:ios:d0d4a23025c973a4a8a512',
    messagingSenderId: '752229000791',
    projectId: 'where-s-the-halal-auth',
    storageBucket: 'where-s-the-halal-auth.appspot.com',
    iosBundleId: 'com.example.wheresTheHalal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAZVmSZLcWtEeHf2UL-NTKYr7FeYI3GRU',
    appId: '1:752229000791:ios:d0d4a23025c973a4a8a512',
    messagingSenderId: '752229000791',
    projectId: 'where-s-the-halal-auth',
    storageBucket: 'where-s-the-halal-auth.appspot.com',
    iosBundleId: 'com.example.wheresTheHalal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ8e-UnCJZGa8rs9m7F7J2BHyD4dSmu1U',
    appId: '1:752229000791:web:c45206f04193fc4fa8a512',
    messagingSenderId: '752229000791',
    projectId: 'where-s-the-halal-auth',
    authDomain: 'where-s-the-halal-auth.firebaseapp.com',
    storageBucket: 'where-s-the-halal-auth.appspot.com',
  );
}
